name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Images
        run: |
          docker build kubeflow_pipeline/0_data -t byeongjokim/mnist-pre-data
          docker push byeongjokim/mnist-pre-data
          docker build kubeflow_pipeline/1_validate_data -t byeongjokim/mnist-val-data
          docker push byeongjokim/mnist-val-data

      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.12'
      
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            kfp==1.1.2

      - name: run pipeline to kubeflow
        run: python pipeline.py

