name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Images
        run: |
          docker build kubeflow_pipeline/0_data -t byeongjokim/mnist-pre-data
          docker push byeongjokim/mnist-pre-data
          docker build kubeflow_pipeline/1_validate_data -t byeongjokim/mnist-val-data
          docker push byeongjokim/mnist-val-data
          docker build kubeflow_pipeline/2_train_model -t byeongjokim/mnist-train-model
          docker push byeongjokim/mnist-train-model
          docker build kubeflow_pipeline/3_embedding -t byeongjokim/mnist-embedding
          docker push byeongjokim/mnist-embedding
          docker build kubeflow_pipeline/4_train_faiss -t byeongjokim/mnist-train-faiss
          docker push byeongjokim/mnist-train-faiss
          docker build kubeflow_pipeline/5_analysis_model -t byeongjokim/mnist-analysis
          docker push byeongjokim/mnist-analysis
          docker build kubeflow_pipeline/6_deploy -t byeongjokim/mnist-deploy
          docker push byeongjokim/mnist-deploy
      
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: mnist-project
          SLACK_MESSAGE: 'Build/Push Images :building_construction: - ${{job.status}}'
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
